using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace sorbe.Utilities
{
    internal static class MusicGenreList
    {
       public static readonly List<string> Genres = new List<string>
        {
            "Pop", "Dance Pop", "Electropop", "Teen Pop",
            "Rock", "Hard Rock", "Soft Rock", "Psychedelic Rock", "Progressive Rock", "Alternative Rock", "Indie Rock",
            "Hip Hop", "Trap", "Boom Bap", "Conscious Hip Hop", "Gangsta Rap",
            "Jazz", "Smooth Jazz", "Bebop", "Swing", "Free Jazz",
            "Classical", "Baroque", "Romantic", "Modern Classical", "Contemporary Classical",
            "Electronic", "House", "Deep House", "Tech House", "Electro House", "Progressive House", "Future House",
            "Trance", "Psytrance", "Uplifting Trance", "Progressive Trance",
            "Techno", "Minimal Techno", "Detroit Techno", "Dub Techno",
            "Dubstep", "Brostep", "Riddim",
            "Drum and Bass", "Liquid Drum and Bass", "Neurofunk", "Jungle",
            "R&B", "Neo-Soul", "Contemporary R&B",
            "Soul", "Funk", "Disco",
            "Country", "Bluegrass", "Country Pop", "Country Rock",
            "Reggae", "Dancehall", "Dub",
            "Blues", "Delta Blues", "Chicago Blues", "Electric Blues",
            "Metal", "Heavy Metal", "Thrash Metal", "Death Metal", "Black Metal", "Power Metal", "Symphonic Metal", "Folk Metal",
            "Punk", "Pop Punk", "Hardcore Punk", "Post-Punk",
            "Gospel", "Contemporary Gospel", "Southern Gospel",
            "Folk", "Indie Folk", "Traditional Folk",
            "Latin", "Reggaeton", "Salsa", "Bachata", "Merengue", "Cumbia",
            "World", "Afrobeat", "K-Pop", "J-Pop", "Celtic",
            "Experimental", "Noise", "Ambient", "Drone",
            "Soundtrack", "Film Score", "Game Soundtrack",
            "New Age", "Meditation Music", "Relaxation Music",
            "Children's Music", "Lullabies", "Sing-Alongs",
            "Comedy", "Parody Music",
            "Holiday", "Christmas", "Hanukkah",
            "Opera", "Operetta",
            "Musical Theatre", "Broadway",
            "Ska", "2-Tone", "Third Wave Ska",
            "Grunge", "Post-Grunge",
            "Shoegaze", "Dream Pop",
            "Synthwave", "Chillwave",
            "Lo-Fi", "Lo-Fi Hip Hop",
            "Indie", "Indie Pop",
            "Electronicore", "Metalcore",
            "Emo", "Screamo",
            "Alternative", "Post-Rock",
            "Post-Hardcore", "Math Rock",
            "Industrial", "Industrial Rock", "Industrial Metal",
            "Swing Revival", "Electro Swing",
            "Tropical", "Tropical House",
            "Chiptune", "Bitpop",
            "Traditional", "World Folk",
            "Polka", "March",
            "Mediterranean", "Flamenco",
            "Tango", "Samba",
            "Bossa Nova", "Latin Jazz",
            "Garage Rock", "Garage Punk",
            "Psybient", "Glitch Hop",
            "Neo-Classical", "Choral",
            "Gregorian Chant", "Liturgical",
            "Renaissance", "Medieval",
            "Sea Shanties", "Work Songs",
            "Field Recordings", "Nature Sounds",
            "Avant-Garde", "Minimalism",
            "Surf Rock", "Rockabilly",
            "Do-Wop", "Barbershop",
            "Krautrock", "Art Rock",
            "Zydeco", "Cajun",
            "Traditional Pop", "Standards",
            "Outlaw Country", "Honky Tonk",
            "Progressive Metal", "Djent",
            "Symphonic Rock", "Neo-Prog",
            "Melodic Death Metal", "Technical Death Metal",
            "Space Rock", "Stoner Rock",
            "Southern Rock", "Swamp Rock",
            "Experimental Hip Hop", "Abstract Hip Hop",
            "Christian Rock", "Christian Metal",
            "Christian Pop", "Worship Music",
            "Hardcore", "Crust Punk",
            "Noise Rock", "No Wave",
            "Chamber Pop", "Art Pop",
            "Ethnic Fusion", "Worldbeat",
            "Afrobeats", "Highlife",
            "Traditional African", "Mbira",
            "Hindustani Classical", "Carnatic Classical",
            "Bollywood", "Indian Pop",
            "Klezmer", "Yiddish Music",
            "Gypsy Jazz", "Manouche",
            "Flute Music", "Didgeridoo Music",
            "Theremin Music", "Avant-Folk",
            "Prog-Folk", "Freak Folk",
            "Alt-Country", "Cowpunk",
            "Neo-Psychedelia", "Acid Rock",
            "Vaporwave", "Future Funk",
            "Cloud Rap", "Plugg",
            "Moombahton", "Zouk",
            "Hardstyle", "Hardcore Techno",
            "Happy Hardcore", "Gabber",
            "Dub Poetry", "Lovers Rock",
            "Americana", "Appalachian",
            "Electro", "Breakbeat",
            "Big Beat", "Nu-Disco",
            "Blue-Eyed Soul", "Northern Soul",
            "G-Funk", "Hyphy",
            "Synthpop", "Electroclash",
            "Eurodance", "Italo Disco",
            "Eurobeat", "Schlager",
            "Viking Metal", "Pirate Metal",
            "Medieval Folk", "Dungeon Synth",
            "Cinematic", "Epic Music",
            "Shoegaze Revival", "Chillstep",
            "Future Bass", "Wave",
            "Electro Swing", "Synthwave", "Noise Ambient", "Dark Ambient"
        };

    }
}
